"""targets

Revision ID: 0002
Revises: 0001
Create Date: 2026-06-13 02:50:01.700634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=2048), nullable=False),
    sa.Column('encrypted_username', sa.LargeBinary(), nullable=False),
    sa.Column('encrypted_password', sa.LargeBinary(), nullable=False),
    sa.Column('origin_allowlist', sa.JSON(), nullable=False),
    sa.Column('sandbox', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('budget_overrides', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_targets_name'), 'targets', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_targets_name'), table_name='targets')
    op.drop_table('targets')
    # ### end Alembic commands ###
